# Generated by Django 2.2.5 on 2020-02-15 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_practice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='feed',
            field=models.ForeignKey(default=3232, on_delete=django.db.models.deletion.CASCADE, to='django_practice.Feed'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='page',
            name='data_published',
            field=models.DateField(auto_now=True),
        ),
    ]
